### ISSUE TITLE
Ruby miner?

### ISSUE THREAD

**Issue by ryana** [verement/cellminer#20]
Hi there,

I'm just starting to look into the bitcoin mining stuff, and this library has been great for helping understand the basics. I know it's a lot slower, but is ruby version of the miner code (ie. Bitcoin::RubyMiner) anywhere?

Thanks!

**Comment by verement** [comment]
No, sorry.

Basically all the miner code is doing is iterating over different nonce values data[19] until SHA256(SHA256(data)) meets the target threshold. It wouldn’t be hard to write in Ruby, but it wouldn’t be terribly useful either.
