### ISSUE TITLE
Running the program

### ISSUE THREAD

**Issue by grifits** [verement/cellminer#24]
Hello, since the writing of your program, many libraries have changed and new versions have appeared. With great difficulty, I installed them all and compiled your program. Given that I never did this for me, it's a feat. But when I try to run it, I get the following error:
(live)ps3min1@redribbon:~/cellminer$ ./cellminer --help
/home/ps3min1/cellminer/cellminer.rb:24:in `require_relative': libspe2.so.2: cannot open shared object file: No such file or directory - /home/ps3min1/cellminer/ext/cellminer.so (LoadError)
	from /home/ps3min1/cellminer/cellminer.rb:24:in `<top (required)>'
	from ./cellminer:21:in `require_relative'
	from ./cellminer:21:in `<main>'
Help please understand this problem. I think it is somewhere on the surface and is associated with setting up directories or paths. But due to lack of experience I can not figure it out. Any hints are welcome.

**Comment by verement** [comment]
The `cellminer.so` depends on `libspe2.so.2` which appears to be missing on your system. This library could be found in the `libspe2-2` package from Debian lenny, but was unfortunately dropped in later Debian releases. You might still be able to use the version from Debian lenny, or you might need to build it from source or otherwise obtain it elsewhere.

**Comment by grifits** [comment]
Hello! Thanks for the answer.
I did everything according to this instruction:
http://ps3montreal.blogspot.ru/2013/11/linux-and-cellminer-install-runthrough.html
there is an installation of this library. I have this library installed. Tell me how to test its work?

**Comment by grifits** [comment]
Thanks again. It is solved !!!
Installed these libraries from the archive:
http://archive.debian.org/debian/pool/main/libs/libspe2/
