### ISSUE TITLE
gcc-4.4-base_4.4.7-4_powerpc.deb

### ISSUE THREAD

**Issue by flygalaxy** [verement/cellminer#28]
Any idea where I can locate this. No luck whatsoever finding it online.

**Comment by grifits** [comment]
I installed this and everything works gcc-4.4-base_4.4.7-2_powerpc.deb .
http://ftp.us.debian.org/debian/pool/main/g/gcc-4.4/gcc-4.4-base_4.4.7-2_powerpc.deb

**Comment by flygalaxy** [comment]
Thanks a lot. Ive been having trouble setting everything up and my son i driving me crazy about this miner.
