### ISSUE TITLE
Segmentation fault on spe_context_create() failure

### ISSUE THREAD

**Issue by verement** [verement/cellminer#3]
When `spe_context_create()` fails, for example if spufs is not mounted on /spu, `rb_raise()` is called within the `Bitcoin::SPUMiner` allocator function. However, during the subsequent process of creating a stack trace, Ruby will segfault.

**Comment by verement** [comment]
The trouble appears to stem from:

> #7  vm_backtrace_push (arg=0xf779fed8, file=272247168, line_no=136, name=0)
>     at vm.c:766

where vm.c:766 tries to reference `RSTRING_PTR(name)` and `name` is NULL.

At this point however I'm not sure whether this is a fault with my implementation or a fault with Ruby.

**Comment by verement** [comment]
Upgrading Ruby to version 1.9.2.180-5 of Debian's ruby1.9.1 package seems to have solved this, so I suspect it was in fact a bug in Ruby.

**Comment by sulewski** [comment]
I get segfault and I do have /spu mounted and I use ruby 1.9.2p180 with YDL.

http://pastebin.com/SHbc1Apu

Any idea?
BTW running cellminer with -d switch doesn't provide any extra information.

**Comment by verement** [comment]
That looks to be a very different problem; it appears to be segfaulting within `spe_program_load()`. Could you open a different tracking issue for that, and include a build log as well as the segfault trace?

Thanks.
