### ISSUE TITLE
Fails when connecting to mining.eligius.st:8337

### ISSUE THREAD

**Issue by n-a-b-s-t-e-r** [verement/cellminer#8]
Thank you for this superb piece of software.
It works fine when connecting to mint.bitminter.com:8332.
It fails when connecting to mining.eligius.st:8337 with the following report:

/home/x/cellminer/cellminer.rb:306:in `pack': can't convert true into String (TypeError)
        from /home/x/cellminer/cellminer.rb:306:in`block in getwork'
        from /home/x/cellminer/cellminer.rb:304:in `each'
        from /home/x/cellminer/cellminer.rb:304:in`map'
        from /home/x/cellminer/cellminer.rb:304:in `getwork'
        from /home/x/cellminer/cellminer.rb:246:in`block (2 levels) in main'
        from /home/x/cellminer/cellminer.rb:245:in `loop'
        from /home/x/cellminer/cellminer.rb:245:in`block in main'

I hope this is helpful.
Kind regards

**Comment by devurandom** [comment]
Same problem here.

@n-a-b-s-t-e-r Can you please edit your report and enclose the error message in `...`? (Note that there needs to be a newline after the first ```.) And please update the Summary with a "[PATCH]" prefix, so it is obvious that the issue includes a working patch.

PATCH:

``` diff
diff --git a/cellminer.rb b/cellminer.rb
index 3c59416..31bdc7a 100644
--- a/cellminer.rb
+++ b/cellminer.rb
@@ -303,7 +303,7 @@ class CellMiner
     # unpack hex strings and fix byte ordering
     work = work.map do |k, v|
       k = k.to_sym
-      v = [v].pack('H*')
+      v = [v.to_s].pack('H*')
       v = (k == :target) ? v.reverse : v.unpack('V*').pack('N*')
       [k, v]
     end
```
